openapi: 3.0.3
info:
  title: Auction API
  version: 1.0.0
  description: Auction Marketplace API
paths:
  /api/auctions/:
    get:
      operationId: auctions_list
      tags:
      - auctions
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auction'
          description: ''
    post:
      operationId: auctions_create
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Auction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Auction'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
          description: ''
  /api/auctions/{auction_id}/bids/:
    get:
      operationId: auctions_bids_list
      parameters:
      - in: path
        name: auction_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - auctions
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bid'
          description: ''
  /api/auctions/{auction_id}/bids/place/:
    post:
      operationId: auctions_bids_place_create
      parameters:
      - in: path
        name: auction_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bid'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bid'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bid'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
          description: ''
  /api/auctions/{id}/:
    get:
      operationId: auctions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this auction.
        required: true
      tags:
      - auctions
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
          description: ''
    put:
      operationId: auctions_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this auction.
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Auction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Auction'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
          description: ''
    patch:
      operationId: auctions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this auction.
        required: true
      tags:
      - auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAuction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAuction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAuction'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auction'
          description: ''
    delete:
      operationId: auctions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this auction.
        required: true
      tags:
      - auctions
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Logout'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Logout'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logout'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/bids/my-bids/:
    get:
      operationId: bids_my_bids_list
      tags:
      - bids
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bid'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Auction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        owner:
          type: string
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        starting_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        current_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        end_time:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/StatusEnum'
        winner:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - current_price
      - description
      - end_time
      - id
      - owner
      - starting_price
      - title
      - updated_at
    Bid:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        auction:
          type: string
          readOnly: true
        bidder:
          type: string
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - auction
      - bidder
      - created_at
      - id
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    PatchedAuction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        owner:
          type: string
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        starting_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        current_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        end_time:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/StatusEnum'
        winner:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Register:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
        confirm_password:
          type: string
          writeOnly: true
      required:
      - confirm_password
      - email
      - id
      - password
    StatusEnum:
      enum:
      - active
      - completed
      - cancelled
      type: string
      description: |-
        * `active` - Active
        * `completed` - Completed
        * `cancelled` - Cancelled
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
